### ISSUE TITLE
Chaining a sequence of POIs

### ISSUE THREAD

**Issue by acycliq** [nytimes/three-story-controls#22]
That's a really nice toolkit, thanks for sharing it.
I have some predetermined points on my scene and my camera goes through them using the StoryPointControls schema.
Is there a way to chain-up all POIs and transition the camera between these POIs without user intervention (no mouse or keyboard) please? 
I want to record a short movie of my project for a demo.
Thanks

**Comment by noisyneuron** [comment]
Hi @acycliq! While the library doesn't provide an explicit way to do this, you can use the `nextPOI` and `prevPOI` functions to programmatically  transition between points. Calling these functions with timeouts should give you what you're looking for. (The [demo](https://github.com/nytimes/three-story-controls/blob/dev/examples/demos/story-points/script.js#L105) calls these functions in response to click events, but that's not necessary)

For eg, to start at the first POI, followed by a 3s transition to POI no.2, followed by a 4s transition to POI no.3 (the timing is cumulative) : 
```
controls.goToPOI(0)
setTimeout( controls.nextPOI, 3000)
setTimeout( controls.nextPOI, 7000)
```

Let me know if that works for your use-case or if you run into any issues with that

**Comment by acycliq** [comment]
Thanks for your prompt reply. For some reason I couldnt make it work. It does execute the first call (`controls.goToPOI(0)`) and then my screen turns black. Pretty weird, it must be something specific to my project I guess.
I also tried to do it with a promise, like:
```
async function flyToROI(num){
    controls.goToPOI(num)
}

flyToROI(0).then(()=>flyToROI(1)).then(()=>console.log('All done'))
```

but i get almost the same unsuccessful results.

I ended-up doing it by the manual way, using the arrows keys while recording the scene

Thanks anyway

**Comment by noisyneuron** [comment]
Hey @acycliq , that's odd as I'm assuming your manual approach would also call `controls.goToPOI(0)` at some point? Are you using `ThreeDOFControls` along with `StoryPointControls` ? If possible, it would be great to see a bit of code to understand what the issue might be -- quite possibly could be a bug in the library :) 

Thanks!

**Comment by acycliq** [comment]
Hmm, no I am not actually using `ThreeDOFControls`  I guess I should, shouldnt I??
The main piece of code relating to the animation is between [this line](https://github.com/acycliq/Izzie/blob/fe3fdfb99d39b451e439558d91f8cb12d824558f/src/scene.js#L68) and [that one](https://github.com/acycliq/Izzie/blob/fe3fdfb99d39b451e439558d91f8cb12d824558f/src/scene.js#L165). 
The animation itself is [here](https://www.dropbox.com/s/nkm54iw2j4xod0d/2022-04-21%2014-38-56.mp4?dl=0). I record that using the keyboard arrows keys.

My code is kinda messy, let me know if you want me to clarify anything.
Many thanks for this amazing tool!

**Comment by acycliq** [comment]
Great! many thanks for looking into this. No idea why my promise also failed, but it doesnt matter now anyway,,,,

**Comment by noisyneuron** [comment]
Hey @acycliq 

The async calls don't actually transform the function to a promise, instead one would do it like so - creating a new promise object that accepts a function as a parameter - and that function in turn has resolve and reject functions as parameters :

```
function goToPoint(point, delay) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      controls.goToPOI(point)
      resolve()
    }, delay)
  })
}

goToPoint(0, 0)
  .then(() => goToPoint(1, 2000))
  .then(() => goToPoint(2, 2000))
```

**Comment by acycliq** [comment]
Oh! That was totally beyond me! Many thanks it is extremely helpful, I will digest it so that I get a better understanding on the async/promise topic.
